

//fetch ('url;).then(message => message.json()).then(json => console.log(json)).catch(error => console.error(error))



/* hacer funcion asyncrona sin congelar la aplicacion
export async function AsyncAwait {
    try {
    const respuesta = await fetch('url');
    const json = await respuesta.json();
    debugger;
    console.log(json);
    } catch{
    console.error('error en la funcion') 
    }
}
*/